# Generated by Django 5.0.6 on 2024-11-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
