# Generated by Django 5.0.6 on 2024-06-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=999991)),
                ('response', models.CharField(max_length=999991)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
